spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: store_user
    password: store_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json

jwt:
  secret: # 👉 Set your Base64 secret key here
